version: '3.1'
services:

  app:
    image: ghcr.io/vysker/cardboardcritic:main
    env_file:
      - .env
    ports:
      - "80:8080"

  db:
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"

  flyway:
    image: flyway/flyway
    command: -url="jdbc:$QUARKUS_DATASOURCE_REACTIVE_URL" -user="$POSTGRES_USER" -password="$POSTGRES_PASSWORD" -baselineVersion=0 -baselineOnMigrate=true migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    env_file:
      - .env
