version: '3.1'
services:

  app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    env_file:
      - .env
    ports:
      - "8080:8080"

  db:
    image: postgres:13-alpine
    env_file:
      - .env
    ports:
      - "5555:5432"
